# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Act4.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget.setStyleSheet("background-color: #396348;")
        #Layout1
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(380, 50, 211, 31))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.Layout1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.Layout1.setContentsMargins(0, 0, 0, 0)
        self.Layout1.setSpacing(3)
        self.Layout1.setObjectName("Layout1")
        self.msg1 = QtWidgets.QTextBrowser(self.verticalLayoutWidget)
        self.msg1.setObjectName("msg1")
        self.msg1.setText("Nombre del archivo")
        self.msg1.setStyleSheet("""
        background-color: #9AB7AC;
        color: black;
        font-weight: bold;
        font-size: 14px;
        font-family: Arial;
        """)
        self.Layout1.addWidget(self.msg1)

        #Recibo1
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(130, 50, 160, 31))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.Recibo1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.Recibo1.setContentsMargins(0, 0, 0, 0)
        self.Recibo1.setObjectName("Recibo1")
        self.int1 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.int1.setObjectName("int1")
        self.int1.setStyleSheet("""
        background-color: #9AB7A1;
        color: black;
        font-weight: bold;
        font-size: 14px;
        font-family: Arial;
        """)
        self.Recibo1.addWidget(self.int1)

        #Recibo2
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(130, 140, 160, 31))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.Recibo2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.Recibo2.setContentsMargins(0, 0, 0, 0)
        self.Recibo2.setObjectName("Recibo2")
        self.int2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.int2.setObjectName("int2")
        self.int2.setStyleSheet("""
        background-color: #9AB7A1;
        color: black;
        font-weight: bold;
        font-size: 14px;
        font-family: Arial;
        """)
        self.Recibo2.addWidget(self.int2)

        #Layout2
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(380, 140, 211, 31))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.Layout2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.Layout2.setContentsMargins(0, 0, 0, 0)
        self.Layout2.setSpacing(3)
        self.Layout2.setObjectName("Layout2")
        self.msg2 = QtWidgets.QTextBrowser(self.verticalLayoutWidget_4)
        self.msg2.setObjectName("msg2")
        self.msg2.setText("Texto a escribir")
        self.msg2.setStyleSheet("""
        background-color: #9AB7AC;
        color: black;
        font-weight: bold;
        font-size: 14px;
        font-family: Arial;
        """)
        self.Layout2.addWidget(self.msg2)

        #Recibo3
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(130, 200, 160, 31))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.Recibo3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.Recibo3.setContentsMargins(0, 0, 0, 0)
        self.Recibo3.setObjectName("Recibo3")
        self.int3 = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.int3.setObjectName("int3")
        self.int3.setStyleSheet("""
        background-color: #9AB7A1;
        color: black;
        font-weight: bold;
        font-size: 14px;
        font-family: Arial;
        """)
        self.Recibo3.addWidget(self.int3)

        #Layout3
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(380, 200, 211, 31))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.Layout3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.Layout3.setContentsMargins(0, 0, 0, 0)
        self.Layout3.setSpacing(3)
        self.Layout3.setObjectName("Layout3")
        self.msg3 = QtWidgets.QTextBrowser(self.verticalLayoutWidget_6)
        self.msg3.setObjectName("msg3")
        self.msg3.setText("Numero de lineas en archivo")
        self.msg3.setStyleSheet("""
        background-color: #9AB7AC;
        color: black;
        font-weight: bold;
        font-size: 14px;
        font-family: Arial;
        """)
        self.Layout3.addWidget(self.msg3)

        #Push button
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(290, 260, 88, 27))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setStyleSheet("""
        background-color: #396348;
        color: white;
        font-weight: bold;
        font-size: 14px;
        font-family: Arial;
        """)

        #Layout4
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(80, 330, 141, 31))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.Layout4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.Layout4.setContentsMargins(0, 0, 0, 0)
        self.Layout4.setSpacing(3)
        self.Layout4.setObjectName("Layout4")
        self.msg4 = QtWidgets.QTextBrowser(self.verticalLayoutWidget_7)
        self.msg4.setObjectName("msg4")
        self.msg4.setText("Numero de vocales")
        self.msg4.setStyleSheet("""
        background-color: #9AB7AC;
        color: black;
        font-weight: bold;
        font-size: 14px;
        font-family: Arial;
        """)
        self.Layout4.addWidget(self.msg4)

        #Layout5
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(390, 330, 211, 31))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.Layour5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.Layour5.setContentsMargins(0, 0, 0, 0)
        self.Layour5.setSpacing(3)
        self.Layour5.setObjectName("Layour5")
        self.msg5 = QtWidgets.QTextBrowser(self.verticalLayoutWidget_8)
        self.msg5.setObjectName("msg5")
        self.msg5.setText("Numero de consonantes")
        self.msg5.setStyleSheet("""
        background-color: #9AB7AC;
        color: black;
        font-weight: bold;
        font-size: 14px;
        font-family: Arial;
        """)
        self.Layour5.addWidget(self.msg5)

        #Layout6
        self.verticalLayoutWidget_9 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(70, 390, 160, 80))
        self.verticalLayoutWidget_9.setObjectName("verticalLayoutWidget_9")
        self.Layout6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_9)
        self.Layout6.setContentsMargins(0, 0, 0, 0)
        self.Layout6.setObjectName("Layout6")
        self.out1 = QtWidgets.QLabel(self.verticalLayoutWidget_9)
        self.out1.setAlignment(QtCore.Qt.AlignCenter)
        self.out1.setObjectName("out1")
        self.out1.setStyleSheet("""
        background-color: #9AB7AC;
        color: black;
        font-weight: bold;
        font-size: 14px;
        font-family: Arial;
        """)
        self.Layout6.addWidget(self.out1)

        #Layout7
        self.verticalLayoutWidget_10 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_10.setGeometry(QtCore.QRect(410, 380, 160, 80))
        self.verticalLayoutWidget_10.setObjectName("verticalLayoutWidget_10")
        self.Layout7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_10)
        self.Layout7.setContentsMargins(0, 0, 0, 0)
        self.Layout7.setObjectName("Layout7")
        self.out2 = QtWidgets.QLabel(self.verticalLayoutWidget_10)
        self.out2.setAlignment(QtCore.Qt.AlignCenter)
        self.out2.setObjectName("out2")
        self.out2.setStyleSheet("""
        background-color: #9AB7AC;
        color: black;
        font-weight: bold;
        font-size: 14px;
        font-family: Arial;
        """)
        self.Layout7.addWidget(self.out2)
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        self.menuMain = QtWidgets.QMenu(self.menubar)
        self.menuMain.setObjectName("menuMain")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuMain.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Analizar"))
        self.out1.setText(_translate("MainWindow", "--"))
        self.out2.setText(_translate("MainWindow", "--"))
        self.menuMain.setTitle(_translate("MainWindow", "Main"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
